Description: Creates a redshift cluster
Resources:
    RedshiftCluster:
        Type: AWS::Redshift::Cluster
        Properties: 
            AllowVersionUpgrade: true
            AutomatedSnapshotRetentionPeriod: 5
            AvailabilityZone: us-east-1
            ClusterIdentifier: ares-redshift-cluster
            ClusterParameterGroupName: 
            ClusterSubnetGroupName: 
            ClusterType: multi-node
            DBName: dev
            Encrypted: true
            MasterUserName: admin
            MasterUserPassword: 
            VpcSecurityGroupIds:
                - 